In [1]:
import numpy as np

metric = "mase"

In [2]:
original_mase = np.load(f"../experiments/electricity_nips/feedforward/{metric}.npy")
np.nanmean(original_mase), np.nanmedian(original_mase), np.nanstd(original_mase)

(1.0186931918485758, 0.5112137347764186, 8.501847716252916)

In [3]:
alternative_mase = np.load(f"../experiments/electricity_nips/feedforward_alternative/{metric}.npy")
np.nanmean(alternative_mase), np.nanmedian(alternative_mase), np.nanstd(alternative_mase)

(2.3118991385744936, 1.7783516932343049, 8.608290849254493)

In [4]:
augmented_mase = np.load(f"../experiments/electricity_nips/feedforward_augmented/{metric}.npy")
np.nanmean(augmented_mase), np.nanmedian(augmented_mase), np.nanstd(augmented_mase)

(1.1753567841364252, 0.6725428725391476, 8.508891578954904)

In [5]:
indexes = [79, 449, 744, 817, 819, 1114, 1187, 1189, 1240, 1484, 1557, 1559, 2111]
len(indexes)

13

In [6]:
original_mase[indexes].mean(), np.median(original_mase[indexes]), np.std(original_mase[indexes])

(34.16964718716724, 5.0703393270333645, 113.73152607609309)

In [7]:
alternative_mase[indexes].mean(), np.median(alternative_mase[indexes]), np.std(alternative_mase[indexes])

(31.394265987296613, 2.2437687354794273, 114.76233520627855)

In [8]:
augmented_mase[indexes].mean(), np.median(augmented_mase[indexes]), np.std(augmented_mase[indexes])

(31.98192046874672, 2.8151578745955934, 114.26526455037416)

In [9]:
original_mase[indexes].mean(axis=1)

array([363.79740112,  23.71681702,   3.35474435,   7.84362808,
         7.2887468 ,   4.75039434,   2.47132658,   7.47936509,
         3.19039923,   4.54002923,   2.51200272,   6.48536663,
         6.77519224])

In [10]:
alternative_mase[indexes].mean(axis=1)

array([365.41287132,   5.60732733,   1.60055783,  10.56085974,
         3.74771959,   1.42368796,   3.69002772,   1.81334436,
         1.30185572,   1.51384458,   3.67866761,   2.37174985,
         5.40294422])

In [11]:
augmented_mase[indexes].mean(axis=1)

array([364.11566301,  13.95921407,   1.42005101,  10.51665884,
         4.05188834,   2.75760544,   2.02237201,   2.68519676,
         1.16082143,   2.14363916,   3.37793084,   2.44646759,
         5.10745759])